{% set name = "pdfme" %}
{% set version = "0.4.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pdfme-{{ version }}.tar.gz
  sha256: c9305a47e7b586339536a3b910fe9d65827d1b8060dd76efd3251c5b42bc1364

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42
    - wheel
  run:
    - python >={{ python_min }}

test:
  source_files:
    - tests
  imports:
    - pdfme
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys -k "not content and not table" tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/aFelipeSP/pdfme
  summary: Create PDFs easily
  license: MIT
  license_file: LICENSE
  doc_url: https://pdfme.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - thewchan
