{% set name = "pdfme" %}
{% set version = "0.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdfme-{{ version }}.tar.gz
  sha256: f694fb08a88ec1790f99e5f8648de6c0bff4db146ecf325f84a8b84bb4512e47

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pdfme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aFelipeSP/pdfme
  summary: Create PDFs easily
  license: MIT
  license_file: LICENSE
  doc_url: https://pdfme.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - thewchan
